# Generated by Django 2.2.5 on 2019-12-11 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastore',
            name='create_date',
        ),
        migrations.AddField(
            model_name='datastore',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datastore',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Girişi Yapan Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='description',
            field=models.TextField(verbose_name='Verinin Tanımı'),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Veri Adı'),
        ),
    ]
