# Generated by Django 2.2 on 2019-12-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_store', '0002_auto_20191211_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Veri Dosyasını ekleyin.'),
        ),
    ]
